services:
  frontend-dev:
    build:
      context: .
      target: development
    ports:
      - 3000:3000
    container_name: frontend-dev
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - /app/node_modules
      - .:/app
